#!/bin/bash
# Welcome message shown each time a Codespace terminal opens
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║         🌾  Kishan Diary – APK Builder               ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║                                                      ║"
echo "║  To build an APK, run these commands:               ║"
echo "║                                                      ║"
echo "║  1. Login to Expo:                                   ║"
echo "║       eas login                                      ║"
echo "║                                                      ║"
echo "║  2. Build the preview APK (recommended):            ║"
echo "║       npm run build:apk                              ║"
echo "║                                                      ║"
echo "║  3. Check build status:                              ║"
echo "║       npm run build:status                           ║"
echo "║                                                      ║"
echo "║  Or use the interactive build script:               ║"
echo "║       bash build-apk.sh                             ║"
echo "║                                                      ║"
echo "║  See APK_BUILD_GUIDE.md for full details.           ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
